### ISSUE TITLE
Add npm package

### ISSUE THREAD

**Issue by zenorocha** [dracula/thelounge#1]
Looks like they encourage themes to be published on npm:
* https://thelounge.chat
* https://www.npmjs.com/search?q=keywords%3Athelounge-theme&page=0&perPage=20

Should we also create a package and edit the install instructions?

**Comment by ronilaukkarinen** [comment]
Oh, missed their standards. As I tried to push it to npm, I realized there is already [another version of Dracula theme for The Lounge](https://github.com/SpaceLenore/thelounge-theme-dracula). Oh snap. As there is no screenshot, I don't know what's different in @SpaceLenore's version. I have used only colors defined [here](https://draculatheme.com/contribute) and flattened it out. Can we join forces?

Another option is for me to release it for different package name like thelounge-theme-dracula-flat or something.

**Comment by zenorocha** [comment]
Let's see what @SpaceLenore thinks. If there's no response we can create a `thelounge-theme-dracula-official`.

**Comment by ronilaukkarinen** [comment]
Yes, let's give this some time. `thelounge-theme-dracula-official` sounds good.

**Comment by SpaceLenore** [comment]
Hi!

I do agree that joining forces sounds like a good idea. I currently don't have any screenshots (but I do plan to add some) you can install the theme with the command `thelounge install thelounge-theme-dracula` to try it out if you wish to. In short, it is the standard Dracula colours and no shadows.

**Comment by ronilaukkarinen** [comment]
I'll test it out soon when I have more time from work. The straight out difference when looking at the code is that I use more CSS vars and style more components like things in mobile and network and channel list, but otherwise feels like a similar approach to mine. Could we add @SpaceLenore as another conributor to this team, merge the repos in some way and publish this repo linked to npm or how should we do this? Suggestions? @zenorocha

**Comment by ronilaukkarinen** [comment]
Finally got time to look into this more carefully.

### @SpaceLenore/thelounge-theme-dracula version:

![Screenshot](https://i.imgur.com/Gaee3C4.png)
![Screenshot](https://i.imgur.com/q4BGCrR.png)

### @dracula/thelounge version:

![Screenshot](https://i.imgur.com/RKS7sdj.png)
![Screenshot](https://i.imgur.com/bnjonnZ.png)

So it seems both are good in their own ways, mine is based on more polished look and parts from [thelounge-theme-crypto](https://github.com/thelounge/thelounge-theme-crypto), some modern preferences like timestamp on the right and some minor fixes for mobile interface, darker sidebar etc., also I have fixed preview contrasts etc., as @SpaceLenore's version has more direct approach and timestamps on the left.

Code-wise I already commented:

> The straight out difference when looking at the code is that I use more CSS vars and style more components like things in mobile and network and channel list, but otherwise feels like a similar approach to mine. Could we add @SpaceLenore as another conributor to this team, merge the repos in some way and publish this repo linked to npm or how should we do this? Suggestions? 

So what do you suggest? These two feel like completely different themes, the biggest differences being perhaps whether the dark or light sidebar is preferred or not. Both use the official colors though. In my opinion two separate themes is not a bad idea either and I'm open to publishing a npm package for my version as well. But before that I want to hear your opinions.

**Comment by SpaceLenore** [comment]
@ronilaukkarinen Thanks for the nice overview of the differences! I agree that our themes are quite different even if we use the same colors so I agree that two different repos and packages might be a good idea.

**Comment by xnaas** [comment]
Would definitely love to see this version of Dracula also pushed to `npm`. Agree it looks like there definitely exists space for both!

**Comment by xnaas** [comment]
Any word on this @ronilaukkarinen / @zenorocha?

**Comment by ronilaukkarinen** [comment]
@xnaas Thanks for the ping! I can go ahead and release this as `thelounge-theme-dracula-official`. I'll let you know!

**Comment by ronilaukkarinen** [comment]
Npm package is now created.

@xnaas Theme can be now installed with `thelounge install thelounge-theme-dracula-official`. Tested it and it works.

@zenorocha Does the page update automatically at https://draculatheme.com/thelounge? I have updated the installation instructions.
